# I used the provided code (Zohan) and updated the image to the latest as I learned in CNE 370 (Kim Rhodes)
# I removed slave1 and slave2 services
# I configured master2 to act as a slave to the other master by adding the --log-slave-updates options
# I updated the configuration so master and master2 are configured as master databases and master2 is a slave to master
# Maxscale was updated to only depend on the two masters
version: '2'
services:
    master:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/master:/docker-entrypoint-initdb.d
        command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3000
        ports:
            - "4001:3306"

    master2:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/master2:/docker-entrypoint-initdb.d
        command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=3001 --log-slave-updates
        ports:
            - "4002:3306"



   maxscale:
        image: mariadb/maxscale:latest
        depends_on:
            - master
            - master2
            
        volumes:
            - ./maxscale.cnf.d:/etc/maxscale.cnf.d
        ports:
            - "4006:4006"  # readwrite port
            - "4008:4008"  # readonly port
            - "8989:8989"  # REST API port
